---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitchensink-bot
  namespace: kitchensink-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kitchensink-bot
rules:
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kitchensink-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kitchensink-bot
subjects:
- kind: ServiceAccount
  name: kitchensink-bot
  namespace: kitchensink-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kitchensink-bot-self-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-provisioner
subjects:
- kind: ServiceAccount
  name: kitchensink-bot
  namespace: kitchensink-bot
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kitchensink-bot-db-pvc
  namespace: kitchensink-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kitchensink-bot
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kitchensink-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kitchensink-bot
    app.openshift.io/runtime: python
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchensink-bot
  template:
    metadata:
      labels:
        app: kitchensink-bot
    spec:
      serviceAccountName: kitchensink-bot
      volumes:
        - name: kitchensink-bot-db-pvc
          persistentVolumeClaim:
            claimName: kitchensink-bot-db-pvc
      containers:
      - image: quay.io/atarazana/kitchensink-bot:1.0.0
        imagePullPolicy: Always
        name: kitchensink-bot
        volumeMounts:
            - name: kitchensink-bot-db-pvc
              mountPath: /db
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom: 
        - secretRef:
            name: kitchensink-bot-env
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kitchensink-bot
  name: kitchensink-bot
  namespace: kitchensink-bot
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: kitchensink-bot
    weight: 100
